[package]
name = "cranelift"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cranelift = "0.85.1"
cranelift-jit = "0.85.1"
cranelift-module = "0.85.1"
